# Generated by Django 3.1.4 on 2020-12-13 20:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='google_id',
            field=models.CharField(default=uuid.uuid4, max_length=200, unique=True),
        ),
    ]
