# Generated by Django 3.1.4 on 2020-12-13 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_book_google_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='year_of_publication',
        ),
    ]
